#!/bin/bash

docker build \
https://github.com/aliasgar-m/ROS-Deployment.git#master:docker \
--cache-from aliasgarm/ros_deployment:latest \
--build-arg CACHEBUST=$(date +%s) \
-t aliasgarm/ros_deployment:latest